### ISSUE TITLE
TypeError: this.destroyInputSpinner is not a function

### ISSUE THREAD

**Issue by svenson08** [shaack/bootstrap-input-spinner#100]
$(element).inputSpinner("destroy") dosn't work

Error Message:
Uncaught (in promise) TypeError: this.destroyInputSpinner is not a function.

**Comment by shaack** [comment]
It seems to work on the demo page: https://shaack.com/projekte/bootstrap-input-spinner/  ("Destroying the spinner")
Under what conditions does it not work?

**Comment by svenson08** [comment]
In my case i use the following condition 
$("input[type='number']").inputSpinner("destroy")
and it raise the error

**Comment by shaack** [comment]
Are there some `input[type='number']` in the page, that are not input spinners? Can you provide a link to a test page where the failure raises?

**Comment by svenson08** [comment]
All of the `input[type='number']` on the page are input spinners.

**Comment by shaack** [comment]
Can you please change the code in line 52 to this:
```js
        if (methodOrProps === "destroy") {
            this.each(function () {
                if (this["bootstrap-input-spinner"]) {
                    this.destroyInputSpinner()
                } else {
                    console.log("element", this, "is no input-spinner")
                }
            })
            return this
        }
```
what happens now in the developer console?

**Comment by svenson08** [comment]
with the changes it works now. No error message or similar. Thanks for the quick support and the changes
