### ISSUE TITLE
Check input have already a spinner

### ISSUE THREAD

**Issue by FireFoxII** [shaack/bootstrap-input-spinner#101]
When spinner has been created for number input, I need to reload it for new input number that comes from ajax/model and seems ok, but when modal is closed, "older" input number have more spinner depending on how many times I have called the modal
![image](https://user-images.githubusercontent.com/4954095/116395913-010fc880-a825-11eb-99b4-5577d1394036.png)
Is there any way to check if input number have already spinner and avoid to add new spinner on it?

**Comment by shaack** [comment]
Yes, `element["bootstrap-input-spinner"]` should be `true` if there was already a spinner created for the element.

**Comment by shaack** [comment]
You can update to version 2.0.12, I added some code to prevent multiple creation.
