### ISSUE TITLE
Handle change event like the native spinner

### ISSUE THREAD

**Issue by jteutenberg2805** [shaack/bootstrap-input-spinner#105]
The native spinner sends the change event when the increase or decrease button is released and not anytime when the value is changed in the input field.

**Comment by shaack** [comment]
OK, if it is so, the bootstrap-input-spinner should change its behaviour because it should act mostly like the native input. I can check this next week.

**Comment by shaack** [comment]
The current version, and the BS 4 compatible version (2.2.0), sends the `change` event now like the native spinner.
