### ISSUE TITLE
Keyboard Stepping Continues After Tabbing

### ISSUE THREAD

**Issue by JeremyV2014** [shaack/bootstrap-input-spinner#116]
Spinner continues to step up/down after tabbing away while holding Up/Down arrow key.

Steps to reproduce:
1. Focus on spinner
2. Press and hold Up or Down key to start stepping 
3. While holding the key down, tab away from the spinner so it loses focus

Expected Result:
Spinner stops incrementing/decrementing after losing focus

Actual Result:
Spinner keeps incrementing/decrementing until hitting the min/max value or indefinitely if min/max isn't set.

**Comment by shaack** [comment]
Thank you for reporting and fixing.
