### ISSUE TITLE
Semicolon is added at the start instead of at the end of the source.

### ISSUE THREAD

**Issue by DamienLaw** [shaack/bootstrap-input-spinner#118]
There is no semicolon at the end of the file
https://github.com/shaack/bootstrap-input-spinner/blob/29b09b4be6bf0dd4af0a0a0cb55594093eeec329/src/bootstrap-input-spinner.js#L372

It is however added at the beginning
https://github.com/shaack/bootstrap-input-spinner/blob/29b09b4be6bf0dd4af0a0a0cb55594093eeec329/src/bootstrap-input-spinner.js#L7

This library, among many other third party libraries are concatenated/bundled together into a big file of libraries to allow browser download more efficiently. Without a semicolon at the end, browser is throwing errors when there are other files concatenated after this library.

![image](https://user-images.githubusercontent.com/14930009/180069242-08c173f6-ec86-4ac6-a9e2-1826bd771cc8.png)

**Comment by shaack** [comment]
I think this is an issue of the other library, because a leading semicolon is the standard. See https://stackoverflow.com/questions/1873983/what-does-the-leading-semicolon-in-javascript-libraries-do
