### ISSUE TITLE
BUG: min max and value change at the same time

### ISSUE THREAD

**Issue by paulzzh** [shaack/bootstrap-input-spinner#119]
#45 
Again in 3.1.12

**Comment by paulzzh** [comment]
![}C%CM_ EIF30EN{7H{07T55](https://user-images.githubusercontent.com/28055560/183130327-9d4c600d-09cf-4653-88ed-a21d29a39bad.png)
![O8R ZDOD }KGZ1VVXTQ(DPR](https://user-images.githubusercontent.com/28055560/183130372-d8ac9c79-fec3-4954-b1e2-1033797063a9.png)
![~T`_(`BYN_P(WAY_9Q_7FJT](https://user-images.githubusercontent.com/28055560/183130384-7416190b-9bca-4d3c-89bd-53ded81089c0.png)

**Comment by shaack** [comment]
Published the fix as 3.1.13
