### ISSUE TITLE
Using the spinner with Vuejs

### ISSUE THREAD

**Issue by highstone** [shaack/bootstrap-input-spinner#12]
Not so much of an issue, rather a question. I really like this implementation of the input spinner, for its simplicity and integration with bootstrap. Were currently evaluating the use of Vuejs for a project where we input spinner is used, any chance we could use the spinner together with Vue?

**Comment by shaack** [comment]
You could wrap it in a Component, like described here: https://vuejsdevelopers.com/2017/05/20/vue-js-safely-jquery-plugin/. Please report, if you try out and it works (or not). :)

**Comment by messerMeinAuto** [comment]
@highstone or you can use this > https://github.com/fengyuanchen/vue-number-input
