### ISSUE TITLE
Minification using Microsoft Visual Studio 22 causes "Identifier has already been declared Error"

### ISSUE THREAD

**Issue by gallge01** [shaack/bootstrap-input-spinner#124]
The issue only presented itself when minified and seems to be a scope related problem when defining variables in the else statement that are to be used outside the scope of the else statement. The actual response from the error provided precious little information other than the delaraction error pointing to this piece of the code. 

== Issue
 if (this["bootstrap-input-spinner"]) {
                console.warn("element", this, "is already a bootstrap-input-spinner")
 } else {
-- variables defined here were causing the issue
}

== Quick Fix
if (this["bootstrap-input-spinner"]) {
     console.warn("element", this, "is already a bootstrap-input-spinner")
     return;
 } 
-- Code continues here not contained within else statement without issue particularly when minified.

**Comment by shaack** [comment]
If there is a bug in Visual Studio, I think, it should be reported to Microsoft.
