### ISSUE TITLE
How to for BootStrap 5 Floating Label Input 

### ISSUE THREAD

**Issue by baxing** [shaack/bootstrap-input-spinner#125]
Hello,

I test to use BootStrap-Input-Spinner with BootStrap 5 Floating labels, but It's not working.
Below image is sample result.
![bs input spinner](https://user-images.githubusercontent.com/54997138/211969530-7fb60610-6852-4ca7-996a-3d7232fee956.png)

You will see that the label will be overlaid and the height of the input field will be reduced.

Please suggest me to work with this Floating Label Input too.

Can I get results like below this or not?
![aim](https://user-images.githubusercontent.com/54997138/211970173-cffe26e6-6b8e-4aa9-b8e2-2432ab95a541.png)

Thanks

**Comment by shaack** [comment]
I think to use floating labels you have to use a custom template with the "template" parameter. See: https://github.com/shaack/bootstrap-input-spinner#template-new

**Comment by baxing** [comment]
> I think to use floating labels you have to use a custom template with the "template" parameter. See: https://github.com/shaack/bootstrap-input-spinner#template-new

Thank you very much, it works for me.

**Comment by baxing** [comment]
Thank you very much, it works for me.
