### ISSUE TITLE
when spinner max value is 0 the upper limit is not respected.

### ISSUE THREAD

**Issue by AndreVianna** [shaack/bootstrap-input-spinner#13]
With the following control:
`<input id="<anythig>" name="<anythig>" type="number" value="0" min="-10" max="0">`
The upper limit of zero is not being respected.
The problem is in line 65 of the file:
`var max = parseFloat($original.prop("max")) || Infinity`
in the case of max = 0 as a valid value 0 || Infinity => Infinity
Proposed correction:
`var max = isNaN($original.prop("max")) ? Infinity : parseFloat($original.prop("max"))`
Only if max is not a valid number the Infinity will be assigned.

**Comment by shaack** [comment]
Many thanks for your report and proposal. It should be fixed now. I slightly modified your code to also consider "" as input:
`var max = isNaN($original.prop("max")) || $original.prop("max") === "" ? Infinity : parseFloat($original.prop("max"))`
