### ISSUE TITLE
Restrict characters in input field

### ISSUE THREAD

**Issue by sinjuangajan** [shaack/bootstrap-input-spinner#14]
`$(document).ready(function() {
    $("input").keydown(function (e) {
        // Allow: backspace, delete, tab, escape and enter
        if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110]) !== -1 ||
             // Allow: Ctrl+A
            (e.keyCode == 65 && e.ctrlKey === true) || 
             // Allow: home, end, left, right
            (e.keyCode >= 35 && e.keyCode <= 39)) {
                 // let it happen, don't do anything
                 return;
        }
        // Ensure that it is a number and stop the keypress
        if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
            e.preventDefault();
        }
    });
});`

**Comment by shaack** [comment]
The current version of the bootstrap-input-spinner now removes unwanted characters automatically.
