### ISSUE TITLE
TypeError: this[0] is undefined

### ISSUE THREAD

**Issue by ptyriver** [shaack/bootstrap-input-spinner#15]
Getting: TypeError: this[0] is undefined bootstrap-input-spinner.js:14:13

Ended up changing:

`            if (this[0]["bootstrap-input-spinner"] && this[0].setValue) {
                this[0].setValue(value)
            }`

to

`            if (this["bootstrap-input-spinner"] && this.setValue) {
                this.setValue(value)
            }`

**Comment by shaack** [comment]
Hi, that can't actually be.  :) Please can you tell me your OS, Browserversion, Bootstrap version, jQuery version.

**Comment by ptyriver** [comment]
Sorry was just about to close this. This was actually an issue within my code elsewhere. I'm no longer able to reproduce this.
