### ISSUE TITLE
Feature request: Adding support for prefix and suffix

### ISSUE THREAD

**Issue by LuckyLuzz** [shaack/bootstrap-input-spinner#18]
Hey,
great lib! Would it be possible for you guys to add support for prefix and suffix? 

Something like that: [https://stackoverflow.com/questions/49796934/add-a-text-suffix-to-input-type-number?noredirect=1&lq=1]()

![grafik](https://user-images.githubusercontent.com/20560944/49868071-9785ef80-fe0c-11e8-9ca4-09ea441fdc53.png)
From Octoprint.org

I made it simply with a span rendering over the input element.
  ```
<div>
<span style="position: absolute; margin-left: 15px; margin-top: 7px; z-index: 1;"> °C </span>

<input type="number" id="Temp" data-decimals="2" value="100"min="0" max="200" step="1" />                                            
</div> 
```
![grafik](https://user-images.githubusercontent.com/20560944/49868292-44f90300-fe0d-11e8-9db9-4215eca3c476.png)

Regards

**Comment by shaack** [comment]
Nice idea. Let's see what we can do.

**Comment by shaack** [comment]
prefix and suffix is now supported. :)

**Comment by LuckyLuzz** [comment]
Awesome! Thank you :)
