### ISSUE TITLE
Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by gumacuk15** [shaack/bootstrap-input-spinner#22]
Hello:

Error on IE:

SCRIPT438: Object doesn't support property or method 'assign'
bootstrap-input-spinner.js (36,9)

Object.assign(config, options) - will be fixed?:) Thank u!

**Comment by shaack** [comment]
Thanks for reporting. :)
With the new 1.10.8 Version I added IE compatibility. Just include the `Object.assign` polyfill like this: 
`<script src="./node_modules/@shaack/polyfills/src/polyfills/object-assign.js"></script>`

Also, the Demopage now works in IE: 
https://shaack.com/projekte/bootstrap-input-spinner/

**Comment by shaack** [comment]
UPDATE: 1.10.9 now has IE support without polyfill.
