### ISSUE TITLE
How to disable typing characters and allowing only numeric input?

### ISSUE THREAD

**Issue by sinjuangajan** [shaack/bootstrap-input-spinner#23]

**Comment by shaack** [comment]
If you enter a non-number character, at the moment the input is marked es invalid and nothing is displayed. 
Do you mean testing and not allowing on "keydown"? What is the use case, why do you need it.

**Comment by sinjuangajan** [comment]
My Intention was to restrict user entering texts in input field. I think Its not  a good practice
Check the link below. I completely disabled editing input field and typing characters inside it. Can you please make changes in plugin like this
[Click Link](http://fenoly.com/abayas?product_id=127)
