### ISSUE TITLE
Dynamically modify minimum / maximum

### ISSUE THREAD

**Issue by AllworxAdvAppDev** [shaack/bootstrap-input-spinner#27]
I want to be able to modify the min / max values of the spinner based on events on the page. If the user selects certain options in the form, then the valid range of values should change based on that.

It looks like the min and max are read and stored in the JS procedure on the call to inputSpinner(), and are not modifiable after that.

**Comment by shaack** [comment]
Now works with Version 1.10.17
https://github.com/shaack/bootstrap-input-spinner/commit/61073b491b3f58e050a3758b5c06a7ad59c05370 
See also the example "Dynamically handling of min, max and step" on the demo page: https://shaack.com/projekte/bootstrap-input-spinner/
