### ISSUE TITLE
autoInterval not cleared when element is disabled

### ISSUE THREAD

**Issue by G33kDude** [shaack/bootstrap-input-spinner#30]
If the button is being held when the element is put into the disabled state, AutoInterval will cause it to keep counting up/down. Also, the `onPointerUp` is not always fired for the disabled element which can cause it to be stuck counting up/down indefinitely.

# To Reproduce

On a page with the following HTML, click and hold on the plus button of the input spinner. Once it begins counting up, release the mouse button.

```html
<input type="number">
<script>
	$('input[type=number]').on('change', function() {
		$(this).prop('disabled', true);
	}).inputSpinner();
</script>
```

# Suggested Fix

In the `updateAttributes` function, add code that checks for the disabled state conditionally resets the `autoIntervalHandler` timer. For example,
```JavaScript
var disabled = $original.prop("disabled")
$input.prop("disabled", disabled)
$buttonIncrement.prop("disabled", disabled)
$buttonDecrement.prop("disabled", disabled)
if (disabled) {
	resetTimer()
}
```

**Comment by shaack** [comment]
Thanks for the report and the suggested fix!
