### ISSUE TITLE
Using a number keyboard on mobile devices / setting the input pattern.

### ISSUE THREAD

**Issue by jboyer87** [shaack/bootstrap-input-spinner#31]
As currently written, the plugin has the "type" property of the resulting input hard-coded as "text". This creates a type="text" input regardless of the original input type (for example, "number"). This hurts the "mobile-friendliness" claim of the addon because if a user tries to interact with an input that is supposed to be of a particular type, the mobile browser will instead revert to full-text input.

**Comment by shaack** [comment]
Good point. Thanks for the recommendation.

**Comment by shaack** [comment]
Okay, I tested it, but it does not work. The native input type="number" ist hopeless not aware of internationalization, which is a core feature of the bootstrap-input-spinner. See: https://stackoverflow.com/questions/13412204/localization-of-input-type-number 
Therefore we can not use another input type than type="text", and a configuration makes no sense.

**Comment by shaack** [comment]
https://stackoverflow.com/questions/25425181/iphone-ios-presenting-html-5-keyboard-for-postal-codes

**Comment by jboyer87** [comment]
Hmm, seems like adding a pattern might do the trick? `pattern="[0-9]*"` for alphanumeric? Good find. Have to do some testing.

**Comment by shaack** [comment]
Yeah, could be. However, there might be problems with the thousand separator and also with the decimal separator.
