### ISSUE TITLE
Change button style

### ISSUE THREAD

**Issue by logarytm** [shaack/bootstrap-input-spinner#33]
First, this library is very helpful, thank you!

Can I change style of the buttons (eg. `btn-outline-secondary` to `btn-secondary`) without hacks?

**Comment by shaack** [comment]
Thanks, yes, you can. :) Via configuration: `buttonsClass: "btn-outline-secondary"`. See "configuration" in the README: https://github.com/shaack/bootstrap-input-spinner#configuration

**Comment by MasterGroosha** [comment]
Hello, I'm trying to make all elements smaller, however, buttons' text doesn't change its position and is not centered after I change height:
![изображение](https://user-images.githubusercontent.com/2780044/66215868-1bc39f00-e6cd-11e9-889a-03fb41d1f5fe.png)

Modified code:
```javascript
        var html = '<div class="input-group ' + config.groupClass + '">' +
            '<div class="input-group-prepend">' +
            '<button style="min-width: ' + config.buttonsWidth + '" class="btn btn-decrement ' + config.buttonsClass + '" type="button">' + config.decrementButton + '</button>' +
            '</div>' +
            '<input type="text" style="max-width:60px; max-height:20px; text-align: ' + config.textAlign + '" class="form-control"/>' +
            '<div class="input-group-append">' +
            '<button style="height:20px; min-width: ' + config.buttonsWidth + '" class="btn btn-increment ' + config.buttonsClass + '" type="button">' + config.incrementButton + '</button>' +
            '</div>' +
            '</div>'
```

**Comment by shaack** [comment]
Did you check out the sizing example on https://shaack.com/projekte/bootstrap-input-spinner/ ?
You just have to add the class `form-control-sm` to the input.

**Comment by MasterGroosha** [comment]
Of course, this is the first thing I tried. But it's still too big for my particular interface.

**Comment by shaack** [comment]
I think this is more a bootstrap problem than a problem with the input-spinner. You have to create a smaller input group in bootstrap to accomplish this. Independent from if the group is rendered in JS or HTML. I think you can't do this with `min-height`. Don't know, maybe this is related: https://github.com/twbs/bootstrap/issues/28901

**Comment by MasterGroosha** [comment]
Thank you! Will try that
