### ISSUE TITLE
Intl is not defined

### ISSUE THREAD

**Issue by raulferras** [shaack/bootstrap-input-spinner#34]
Some browsers do not support the object `Intl`.

If do not want to support older browsers, is there a way to disable this feature?

**Comment by shaack** [comment]
You could use a shim or polyfill like https://github.com/andyearnshaw/Intl.js

**Comment by shaack** [comment]
Dit it worked? If yes, please tell me and for which Browser, in that case I could update the documentation. Thanks!

**Comment by raulferras** [comment]
Yes sorry. I had reports of Internet explorer (I think it was IE 9) complaining about it.
