### ISSUE TITLE
Change data-decimals attribute dynamically

### ISSUE THREAD

**Issue by vladislav-vasilyev** [shaack/bootstrap-input-spinner#35]
I have `<input type="number" id="input-spinner" data-decimals="1" ...>` in my html and I try to change data-decimals attribute dynamically from `'1'` to `'0'` but it doesn't work, nothing changes:
`$('#input-spinner').prop('data-decimals', '0');`
How can I fix it?

**Comment by shaack** [comment]
Yes, thanks, for reporting. This is a bug, changing data-dezimals is not handled correct dynamically.

**Comment by shaack** [comment]
Fixed and example added
See: https://shaack.com/projekte/bootstrap-input-spinner/ 
"Dynamically handling of min, max, step and data-decimals"

**Comment by shaack** [comment]
Please note: When changing `data-decimals` dynamically you may have to use jQuerys `attr()` instead of `prop()`, bacause it is an attribute, not a property.
https://stackoverflow.com/questions/36663690/jquery-prop-returns-undefined-while-attr-works-as-expected-for-data

**Comment by vladislav-vasilyev** [comment]
@shaack Thank you for the fix but I need to change data-decimals attribute dynamically for the following case. I have the `step="0.5"` and I need to display integer with `data-decimals="0"` and float with `data-decimals="1"` like this:
`0, 0.5, 1, 1.5, 2, 2.5, 3, 2.5, 2, 1.5, 1, ...`

I tried to do it by the condition but it doesn't work as expexted. When I set the `.attr('data-decimals', '0');` the step increases to 1 forever and I can't decrease the value of the input:
`$('#input-spinner').change((e) => {`
&nbsp;&nbsp;`if (+e.target.value % 1 === 0) {`
&nbsp;&nbsp;&nbsp;&nbsp;`$(e.target).attr('data-decimals', '0');`
&nbsp;&nbsp;`}	else {`
&nbsp;&nbsp;&nbsp;&nbsp;`$(e.target).attr('data-decimals', '1');`
&nbsp;&nbsp;`}`

Any ideas?
