### ISSUE TITLE
Usage with angularJS. Increment decrement doesn't work.

### ISSUE THREAD

**Issue by visrahane** [shaack/bootstrap-input-spinner#36]
This is what I tried - 

//included js by downloading src file :  bootstrap-input-spinner.js

<script th:src="@{/js/bootstrap-input-spinner.js}"></script>
	<script>
    	$("input[type='number']").inputSpinner();
	</script>

I see the spinner but click on "+"/"-" doesn't change the value.

<img width="476" alt="Screen Shot 2019-04-17 at 5 56 32 PM" src="https://user-images.githubusercontent.com/8768717/56329846-5eeb7f00-613a-11e9-9a0d-3c7f660cf5ad.png">

Am I missing something here?

Another weird thing I noticed - if I init $("input[type='number']").inputSpinner(); in a my page js file for eg:
$(document).ready(function () {
	$("input[type='number']").inputSpinner();
}

+/- click works but placeholders are shown incorrectly
<img width="829" alt="image" src="https://user-images.githubusercontent.com/8768717/56330381-af63dc00-613c-11e9-8dea-1820667c4d3c.png">
so here, instead of 1, I see 0 in the textbox of spinner

**Comment by shaack** [comment]
You are using the Spinner with angular js?
