### ISSUE TITLE
Enable spinner via ajax

### ISSUE THREAD

**Issue by jzelvoort** [shaack/bootstrap-input-spinner#38]
First, this library is very helpful, thank you!

At some point in my project I build a dynamic form after an AJAX call. The form is dynamically placed in a modal and launched. The spinner however won't initialize... The spinners which are in the page at pageload are working fine.

Any ideas?
Thanks

**Comment by shaack** [comment]
When the modal is nor existing on initialisation `$("input[type='number']").inputSpinner()`, you must maybe re-initialize the elements in the modal. Can you provide a webpage, where this failure is shown?

**Comment by jzelvoort** [comment]
Hi Shaack,

I did re-initialize before I show the modal. Now I re-initialize the input after the modal is shown. Now it works ;-)

Thanks for your fast answer and pushing me in the right direction!!

Kind regards,
Jeroen
