### ISSUE TITLE
plus and minus icons are not showing

### ISSUE THREAD

**Issue by hasintha** [shaack/bootstrap-input-spinner#39]
Hello there

I'm running this in localhost. The plus and minus sign of the spinner are not showing up. The browser only shows a default spinner

here is my page

`
<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="css/styles.css" >
  
    
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script src="http://localhost/front-end/js/bootstrap-input-spinner.js"></script>

    <script>
        jQuery("input[type='number']").inputSpinner()
    </script>

    <script>
      jQuery( function() {
        jQuery( ".datepicker" ).datepicker();
      } );
    </script>
    

  </head>
  <body>

    <div class="form-container">

      <form class="form-horizontal" action="" method="POST">

          
          <div class="form-group">
            <label class=" control-label" for="adults">Adults</label>
            <div class="">
              <input name="adults" type="number" value="0" min="0" max="5" step="1" />
            </div>
          </div>

          
          <div class="form-group">
            <label class="control-label" for="children">Children</label>
            <div class="">
               <input name="children" type="number" value="0" min="0" max="5" step="1"/>
            </div>
          </div>

          
          <div class="form-group">
            <label class=" control-label" for="infants">Infants</label>
            <div class="">
              <input name="infants" type="number" value="0" min="0" max="5" step="1"/>
            </div>
          </div>

         

          </fieldset>
          </form>

         </div>

   </body>
</html>

`

**Comment by shaack** [comment]
That's pretty much more of a problem with the code than with the inputspinner. What I see is that the HTML is not valid, e.g. the opening fieldset tag is missing. If you make a version available online, I can take a closer look.

**Comment by hasintha** [comment]
@shaack Thanks for the quick reply mate. Sorry for the late reply.  I've added you as a collab for the repo. the sources are inside the front-end folder. I have removed the fieldset tag.

https://github.com/hasintha/travelport/tree/master/front-end

**Comment by hasintha** [comment]
It worked after I wrapped the function call around a jQuery();

` jQuery( function() {
        jQuery("input[type='number']").inputSpinner();
      });`

**Comment by shaack** [comment]
Thanks for the feedback. It looks like a timing problem. You cant initialise the spinner before its HTML is rendered. So it should also work, when you put the code `jQuery("input[type='number']").inputSpinner();` at the bottom of your html or if you use `jQuery(document).ready([...]);` to initialize the spinner.

**Comment by hasintha** [comment]
Got it. Cheers mate.
