### ISSUE TITLE
Updating the value doesn't show on the input spinner

### ISSUE THREAD

**Issue by highstone** [shaack/bootstrap-input-spinner#4]
For some strange reason, the value of the input spinner is not shown (or updated) when it's set manually using a jQuery statement like:

`$('input.input-spinner').val(count);`

Is there something obvious I'm missing? Consider the html fragments below. When I debug the code and inspect the spinner object, I can see the value is updated but the UI doesn't reflect this.

```
<div class="form-row">
        <div class="col-2">
            <input class="input-spinner" type="number" min="0" max="25" step="1" />
        </div>
        <div class="col">
            <button class="btn btn-primary">Set!</button>
        </div>
</div>    
```

And the script
```
<script>

        $('button.btn-primary').on('click', function (e) {
            var count = 10;

            console.log("Setting count on spinner: " + count);
            
            var spinner = $(this).closest('.form-row').find('input.input-spinner');
            spinner.val(count);
        });

        $('input.input-spinner').on('change', function (e) {
            var count = $(this).val();
            if (count === "")
                return;

            console.log("Spinner count: " + count);
        })

        $('input.input-spinner').InputSpinner();        

</script>
```
Also, in the fragment above, the Change events is fired on initializing the spinner, is that a known issue?

**Comment by highstone** [comment]
Yep, that does the trick! Thanks for the superfast response, I was about to pull my hair on it ;-)

**Comment by shaack** [comment]
created enhancement https://github.com/shaack/bootstrap-input-spinner/issues/6

**Comment by shaack** [comment]
Now works with `$.fn.val()`, see updated examples: https://shaack.com/projekte/bootstrap-input-spinner/

**Comment by AntykT** [comment]
I'm have problem with changes two attributes: in first time I'm changing "min" attr (successfully) and after trying to change value by $(sel).val().  
`<input type="number" class="form-control calc-event" id="stay" name="stay" value="2" min="2" max="365" step="1"/> `
and jquery
`
$("#stay").attr("min", 1);
$("#stay").val( 1 );
`

When requesting value by val(), I see that the  value is changed but displayed value is not refreshed. When I'm not setting "min"  attr, value changing without any problem. "min" attr is strongly necesery. Any possible solution?

**Comment by AntykT** [comment]
> I'm have problem with changes two attributes: in first time I'm changing "min" attr (successfully) 
found a solution :)
in the input tag, the "min" attribute must be placed before the "value" attribute, i.e. instead of
<input type = "number" class = "calc-event of the form control" id = "stay" name = "stay" value = "2" ** min = "2" max = "365" step = "1" />
should be
<input type = "number" class = "calc-event of the form control" id = "stay" name = "stay" min = "2" value = "2" max = "365" step = "1" /> and first change the "min" attribute :)
