### ISSUE TITLE
Unwanted thousand seperator

### ISSUE THREAD

**Issue by CybrZr00** [shaack/bootstrap-input-spinner#42]
Hi,

Just a note to those not wanting any separators/grouping (and maybe a feature request), eg when using number input for years or because of issues parsing the symbol. 

obviously, you could add another property/variable and use that, but as a quick fix, this works.

on line 76 you should find this:

            var numberFormat = new Intl.NumberFormat(locale, {
                minimumFractionDigits: decimals,
                maximumFractionDigits: decimals               
            });
simply add useGrouping: false to the options, making:

            var numberFormat = new Intl.NumberFormat(locale, {
                minimumFractionDigits: decimals,
                maximumFractionDigits: decimals,
                useGrouping: false
            });

Thanks!

**Comment by shaack** [comment]
fixed with the attribute "data-digit-grouping", thanks to maurojs10.
