### ISSUE TITLE
Disable Bootstrap validation

### ISSUE THREAD

**Issue by JeremyWinalist** [shaack/bootstrap-input-spinner#43]
Hi,
Is it possible to disable bootstrap validation ? Because check appears on top of input values.
Thanks.
![image](https://user-images.githubusercontent.com/49526279/63250356-bf670600-c26b-11e9-932c-87bd61df6a3d.png)

**Comment by shaack** [comment]
What kind of bootstrap validation do you use? I think it depends on tag attributes like „class“, „required" or „data-*„ how inputs act in bootstrap.
The inputSpinner does not any validation.

**Comment by JeremyWinalist** [comment]
@shaack I use the default one, provided by Bootstrap (which is browser validation but with classes). See [Bootstrap Documentation](https://getbootstrap.com/docs/4.3/components/forms/#validation). In fact, I would like to use your spinner but disable input. The easiest way would be to add `readonly` to resulting input text. But I don't see an option in configuration object.
