### ISSUE TITLE
Bug on Safari and iOs devices

### ISSUE THREAD

**Issue by Fred-Guile** [shaack/bootstrap-input-spinner#46]
Hello,

it seems that Apple has stopped using the Intl librairy :

line 238 : ReferenceError: Can't find variable: Intl

Is there a way to fix it ?

Thank you

**Comment by shaack** [comment]
Hi, what is your OS and Browser Version. Thanks.

**Comment by Fred-Guile** [comment]
On windows, Safara 5.1.4 but it's also not working on my ipad.

There's another error with mutationobserver.

**Comment by shaack** [comment]
Windows Safari is not supported. What is your iOS and Safari Version on the iPad?

**Comment by Fred-Guile** [comment]
iOs and Safari version is 9.3.5

**Comment by shaack** [comment]
This iOS is from August 25, 2016. If you want to support such old versions, you have to use a shim, like described here: https://github.com/shaack/bootstrap-input-spinner/issues/34
Please, next time, search the existing issues before creating a new one. Thanks. :)
