### ISSUE TITLE
Setting the form-control-sm or form-control-lg

### ISSUE THREAD

**Issue by highstone** [shaack/bootstrap-input-spinner#5]
Can you add the configuration option to set the form-control class? Eg. form-control-sm or form-control-lg?

**Comment by shaack** [comment]
Hi! This already works, but with the `input-group` class. I added an example: 
https://shaack.com/projekte/bootstrap-input-spinner/
Just use: `$("input.small").InputSpinner({groupClass: "input-group-sm"})` and `$("input.large").InputSpinner({groupClass: "input-group-lg"})`
