### ISSUE TITLE
Empty value reset to zero when changing attributes

### ISSUE THREAD

**Issue by maurojs10** [shaack/bootstrap-input-spinner#51]
### Context
A number input has an empty value and then that input has some of its attributes changed.

### Current Behavior
The plugin resets the value to zero

### Expected Behavior
The value should remain empty.

### Example
https://jsfiddle.net/maurojs10/er4qkxwo

**Comment by shaack** [comment]
Fixed with https://github.com/maurojs10/bootstrap-input-spinner/commit/c358907c675607e4911f979321c5e5eaf8e45639
