### ISSUE TITLE
Delay after keyup at change event?

### ISSUE THREAD

**Issue by mllapps** [shaack/bootstrap-input-spinner#54]
I want to use this nice library to send AJAX data if value changed. But with the normal solution it will send the data to often. Do you have an idea to call the change event some seconds after the keyup event detected and if a user press it again the timeout will reset.

**Comment by shaack** [comment]
Hi, you have to throttle or debounce the calls. It's explained here https://codeburst.io/throttling-and-debouncing-in-javascript-b01cad5c8edf 
Debouncing is done very simple like this:
```
clearTimeout(this.apiCallDebounce) 
this.apiCallDebounce = setTimeout(() => {
    apiCall()
}, 500)
```
This will wait 500ms of nothing happens before doing the apiCall().

**Comment by mllapps** [comment]
Thank you for the fast response. The solution works!!!
