### ISSUE TITLE
"Invalid regular expression" error when thousandSeparator is empty string

### ISSUE THREAD

**Issue by Roman-** [shaack/bootstrap-input-spinner#55]
**How to reproduce:**

1. Change system region format to Russian.
2. Click on input spinner to input value by typing
3. Type any number

You should see an error:
`bootstrap-input-spinner.js:256 Uncaught SyntaxError: Invalid regular expression: /\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at parseLocaleNumber (bootstrap-input-spinner.js:256)
    at HTMLInputElement.<anonymous> (bootstrap-input-spinner.js:113)`

**Reasoning**
On Russian locale, there's no separator for thousands. Hence,[ this line](https://github.com/shaack/bootstrap-input-spinner/blob/5848e2056292de2c07a99d6ceacf51f073556216/src/bootstrap-input-spinner.js#L253)
`                var thousandSeparator = numberFormat.format(1111).replace(/1/g, '')`
produces an empty string. Then the [next line](https://github.com/shaack/bootstrap-input-spinner/blob/5848e2056292de2c07a99d6ceacf51f073556216/src/bootstrap-input-spinner.js#L256)
`new RegExp('\\' + thousandSeparator, 'g'), '')`
makes a regexp `/\/`, which makes an error and doesn't change the input spinner val.

**Comment by Roman-** [comment]
An easy fix can be to replace this line
`var thousandSeparator = numberFormat.format(1111).replace(/1/g, '')`
with this
`var thousandSeparator = numberFormat.format(1111).replace(/1/g, '') | ' '`

**Comment by shaack** [comment]
Okay, I switched the locale, but get no error. Which Browser? In Chrome, it seems to work.
<img width="842" alt="Bildschirmfoto 2019-11-14 um 10 31 52" src="https://user-images.githubusercontent.com/832120/68844393-024d4400-06ca-11ea-8b23-3864ca67f62f.png">

**Comment by Roman-** [comment]
Okay, looking deeper, after line 246 I've added this to debug:
`console.log(locale, numberFormat.format(1111));`
and it gave me this: `es-AU 1111`
My Chrome version: Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by Roman-** [comment]
Yep, I've forgotten that I've decided to learn Spanish language and have added Spanish (apparently in Google settings) to the list of languages.
One way or another, this regex construction `'\\' + thousandSeparator` assumes that `thousandSeparator` has to be strictly one character long string (not always true) that has to be escaped in regex (also may not be true). This is a dangerous assumption which may cease to work in some cases, like with the `es-AU` locale here.
One more notice is that my OS is Ubuntu 16.04 LTS.

**Comment by shaack** [comment]
You are right. Looks like the localization feature needs to be reworked. Do you have an idea how to fix it? I can think about it next week, this week I have to much customer stuff to do.

**Comment by shaack** [comment]
I found some ideas here: https://stackoverflow.com/questions/11665884/how-can-i-parse-a-string-with-a-comma-thousand-separator-to-a-number

**Comment by villu164** [comment]
https://github.com/shaack/bootstrap-input-spinner/pull/62/files
ran into same issue, created fix

**Comment by villu164** [comment]
@shaack, any progress?

**Comment by czachor** [comment]
Same here with Polish locale.

Firefox reports an error in the console when I'm trying to insert input's value manually:
> SyntaxError: \ at end of pattern 3 plugins.js:274:14
    parseLocaleNumber https://localhost/foobar/js/plugins.20161010.js:269
    inputSpinner https://localhost/foobar/js/plugins.20161010.js:122
    jQuery 5
        dispatch
        handle
        trigger
        simulate
        i

In Chrome:
> Uncaught SyntaxError: Invalid regular expression: /\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at parseLocaleNumber
    at HTMLInputElement.<anonymous>
    at HTMLInputElement.dispatch (jquery-3.5.1.min.js:2)
    at HTMLInputElement.v.handle (jquery-3.5.1.min.js:2)

**Comment by shaack** [comment]
Fixed with https://github.com/shaack/bootstrap-input-spinner/commit/1e3de85df27da1fbd89827c65a4e2ce0d37dffd7
