### ISSUE TITLE
destroy

### ISSUE THREAD

**Issue by qxygene** [shaack/bootstrap-input-spinner#57]
how to destroy instances?

**Comment by shaack** [comment]
For what do you need this?

**Comment by qxygene** [comment]
it creates multiple instances on each call at same page

**Comment by thijstriemstra** [comment]
+1 I also need this, to destroy instances inside a bootstrap modal that is closed.

**Comment by shaack** [comment]
Okay, I can implement it in January, but till Christmas, no time, sorry.

**Comment by thijstriemstra** [comment]
That's okay, I added a  `$(element).destroy()` that'll work till then. Let me know if you want a pull request.

line 24:
```javascript
$.fn.destroy = function () {
        if (this[0] && this[0]["bootstrap-input-spinner"] && this[0].destroy) {
            var element = this[0];
            setTimeout(function () {
                element.destroy()
            })
        }
    }
```

line 109:
```javascript
$original[0].destroy = function () {
                destroy()
            }
```
line 141:
```javascript
function destroy() {
                observer.disconnect();
                resetTimer();
                $input.off("paste input change focusout");
                $original.next('div').remove();
            }
```

**Comment by qxygene** [comment]
thank you

**Comment by shaack** [comment]
Hi @thijstriemstra , if you could create a pull request, that would be nice. Thank you!

**Comment by thijstriemstra** [comment]
>  if you could create a pull request, that would be nice. Thank you!

see #59

**Comment by shaack** [comment]
Thanks! Well done. But I think it shouldn't destroy the original element because it didn't create it either. I will modify your approach, when i find the time, will be in January I think.

**Comment by shaack** [comment]
It should return to the exact state before creation. 

**Best practice for the Syntax** 

jQuery is recommending (and using in UI) the string method: https://stackoverflow.com/questions/1117086/how-to-create-a-jquery-plugin-with-methods

=> `$(element).inputSpinner("destroy")`
