### ISSUE TITLE
Doubling the code

### ISSUE THREAD

**Issue by sashabeep** [shaack/bootstrap-input-spinner#64]
Script creates two widgets at the time on every number input

<img width="283" alt="Снимок экрана 2020-04-01 в 16 58 27" src="https://user-images.githubusercontent.com/5689796/78146116-65056900-743a-11ea-8a73-a0f92d6df60d.png">

Two input groups
<img width="667" alt="Снимок экрана 2020-04-01 в 16 59 48" src="https://user-images.githubusercontent.com/5689796/78146728-3c31a380-743b-11ea-9ebd-9f95cc80d853.png">

call:
```javascript
$("input[type='number']").inputSpinner();
```

**Comment by shaack** [comment]
Sorry, but it does not. It works on the demo page and all other usages: https://shaack.com/projekte/bootstrap-input-spinner/ 
I think you are calling it twice maybe.

**Comment by sashabeep** [comment]
@shaack as i see, there is no check in the code if widget is applied or not - it can cause this "double wrap" behavior

**Comment by shaack** [comment]
To check for all possible usage failures, would bloat the code unnecessary. I prefer clean and easy readable code, therefor I will not check all possible usage failures. If you call the widget twice, there is an misconception or failure in your code.
