### ISSUE TITLE
Localisation based on project needs

### ISSUE THREAD

**Issue by perarg** [shaack/bootstrap-input-spinner#67]
Here is a real scenario:
I am working on a project where a user has to input an amount in Euro. The project is local-based in Greece so the locale is strictly with comma `,` as decimal separator and dot `.` as thousand seperator.

I am using a macOS environment which is in english with greek localisation. But all my browsers (chrome, firefox, safari) are in english and none of them doesn't seem to understand my localisation. So the display of this input field for decimal is with dot `.` instead of comma.
I assume that there are a lot of others with the same configuration as mine.

Think also that a greek user who lives in a foreign country and she has to complete the form with the amount field of course in Euro currency but her browser configuration is in different localisation.

It's frustrating. I understand that it may be a browser issue, but as developers we have to give the right UX to our users.

I propose to bring back as config option the locale and keep as fallback the `navigator.language`. If there is a multi-language website and there is need of both decimal point display, the locale  could be loaded dynamically in config through language url parameter.

**Comment by shaack** [comment]
When you look at other Standard-Inputs like input[type="date"] the locale is used always from the browser. A behaviour to use a configured locale is not standard and different from other standard html input elements.
Also, we have the problem, that a central locale configuration will not work together with the inputmode="decimal" from https://github.com/shaack/bootstrap-input-spinner/pull/58 
Do you know that, for the application backend the value is stored in standard US-notation? The view from the input-spinner is different from the value of the element. View => internationalized (like 1.200,40 for DE), value => Standard US (like 1200.40). So with ($input.val()) you will always get the standard float.
