### ISSUE TITLE
"An invalid form control with name='' is not focusable" when "required"

### ISSUE THREAD

**Issue by mucahittopal** [shaack/bootstrap-input-spinner#73]
I found the solution like this ;

> function updateAttributes() {
                // copy properties from original to the new input
                **$input.prop("name", $original.prop("name"))
                $original.removeAttr("name")**
                $input.prop("required", $original.prop("required"))
                $input.prop("placeholder", $original.prop("placeholder"))
.
.
.

**Comment by shaack** [comment]
Does it makes sense? After that you have two inputs in one form with the same "name", one with the correct value ($original) and one with a localised value ($input).

**Comment by mucahittopal** [comment]
I think it makes sense :) Because new $input "name" created same as original and  removed $original "name" on input

**Comment by shaack** [comment]
Ok, right. :) But why? What is the benefit? And how do you handle localized numbers on the server? en: 1,200.5 is in de: 1.200,5 and in es 1200,5 and in ru 1 200,5

**Comment by mucahittopal** [comment]
This is benefit of browser checking validation. Our localized numbers : 1.200,5

Like localized DE

**Comment by shaack** [comment]
You have only users from one country? Browser checking validation works without your modification of I did not get what you mean. The value is automatically copied to $original.

**Comment by mucahittopal** [comment]
Yep!
Browser checking validation works but when use to  "required" I am getting an error on developer console "An invalid form control with name='adet' is not focusable."

**Comment by shaack** [comment]
Ahhh, ok! Now we get to the real problem. https://stackoverflow.com/questions/22148080/an-invalid-form-control-with-name-is-not-focusable 
You are right, there is an issue with invisible "required" fields, so I think it is the "required" attribute we must remove from "$original".

**Comment by shaack** [comment]
Fixed the "required" Problem in 1.13.13. Does it work for you now?

**Comment by mucahittopal** [comment]
Thanks bro, it's worked :)
