### ISSUE TITLE
hidden attribute

### ISSUE THREAD

**Issue by gbjbaanb** [shaack/bootstrap-input-spinner#76]
I am updating all number fields using a selector, but this means that any hidden field is automatically converted to the spinner input group, and becomes visible. I noticed the properties of the field are copied to the new input group, would it be a good idea to also copy a hidden attribute too. 

I can (and have) changed my selector to ignore hidden fields, but i think sometimes you want the field to be hiiden and then appear based on some other action, so putting this feature in the library makes sense (to me).

Adding this to the updateAttributes function appears to work fine: 
                $inputGroup.attr("hidden", $original.attr("hidden"))

**Comment by shaack** [comment]
I think it speaks nothing against it. I think I will add this.

**Comment by shaack** [comment]
...other global attributes should be handled also, see https://github.com/shaack/bootstrap-input-spinner/issues/77
