### ISSUE TITLE
Is possible to have this layout? (enhancement: allow templating)

### ISSUE THREAD

**Issue by alvinkonda** [shaack/bootstrap-input-spinner#78]
I know i can do this:

![Screenshot 2020-09-07 at 9 28 02 AM](https://user-images.githubusercontent.com/273284/92360056-830f7d80-f0ec-11ea-9392-bb234d3c969f.png)

But can i do this?

![Screenshot 2020-09-07 at 9 28 02 AM2](https://user-images.githubusercontent.com/273284/92360703-8ce5b080-f0ed-11ea-857e-35e4a1270d52.png)

**Comment by shaack** [comment]
It's a change I've been planning for a while now, namely the possibility to configure a template for the look. Basically it is about adapting the code behind 'var html =' or putting it into the configuration. How urgent is this requirement?

**Comment by alvinkonda** [comment]
Thank you for your quick reply!

No problem, take your time. Basically as you can see from the screenshot below which is currently on my site, it would be nice to have the "Qty" field as the variant selectors above. Otherwise, stil it looks fine the way it is now.

![Screenshot 2020-09-07 at 12 24 44 PM](https://user-images.githubusercontent.com/273284/92378027-62075680-f105-11ea-8a47-d1ebc4d98989.png)

**Comment by shaack** [comment]
Templating works now! See: https://shaack.com/projekte/bootstrap-input-spinner/
 "Styling with templates (New!)" :)
