### ISSUE TITLE
Change event is fired on (page) initialization

### ISSUE THREAD

**Issue by highstone** [shaack/bootstrap-input-spinner#8]
For some reason, when I hook up the code below, the change event is fired when the InputSpinner is initialized. Is there any reason for this? Or how to prevent this? 

```
$('input.input-spinner').on('change', function (e) {
  var count = $(this).val();        
  console.log("Spinner count has changed: ", count);
});       

$('input.input-spinner').InputSpinner();

**Comment by shaack** [comment]
This was a bug, thanks for reporting. It should be fixed now.

**Comment by highstone** [comment]
Awesome! Thanks for the super fast replies!

**Comment by shaack** [comment]
Thanks back to you for the detailed reporting and suggestion of good enhancements. 👍 It is very nice to get the response from someone using it in production.

**Comment by highstone** [comment]
I know. Love the simplicity and functionality of the spinner. It just works!
