### ISSUE TITLE
Issue with ajax data

### ISSUE THREAD

**Issue by alvinkonda** [shaack/bootstrap-input-spinner#80]
Hi,

I'm doing some sort of infinite scroll with ajax and I know that I can re-initialize the plugin after ajax call but that causes duplicates on the inputs that are already on place. Any simple way i can go around this?

Thanks

**Comment by shaack** [comment]
Add a class to the element and exclude this class when selecting
`$("input[type='number']").not(".b-i-s-initialised").addClass("b-i-s-initialised").inputSpinner();`

**Comment by alvinkonda** [comment]
Thank you.

I have gone ahead with this code which seems to work fine across all instances when using InputSpinner, however i suggest you update the docs for this kind of cases. Again thank you very much for this great script.

```
// Initiliate bootstrap input spinner
// https://shaack.com/projekte/bootstrap-input-spinner
window.initInputSpinner = function() {
    $('input[type="number"]').not(".init").addClass("init").inputSpinner();
}
initInputSpinner()

// Do various work after any ajax call completes
$(document).ajaxComplete(function() {
    initInputSpinner()
})
```

**Comment by shaack** [comment]
Thanks
