### ISSUE TITLE
min="0" value is ignored

### ISSUE THREAD

**Issue by 5ulo** [shaack/bootstrap-input-spinner#83]
It is visible also on the [Demo page](https://shaack.com/projekte/bootstrap-input-spinner/) that the min value is ignored and you can click to minus infinity. Min value works only if x > 0.. so it can be min 0.1 but not 0. Tested with latest Chrome and Firefox on MacOS, browsers on Android

````html
<input type="number" min="0" max="100" step="1" value="1" class="fld--pcs">
````

````javascript
$('input.fld--pcs').inputSpinner({
    groupClass: 'form-group--pcs',
    buttonsOnly: true,
    buttonsClass: 'btn-light'
});
````

edit: it works if I modify `bootstrap-input-spinner.js` around line 262
````javascript
// min = parseFloat($original.prop("min")) || -Infinity // this is the old one
min = isNaN($original.prop("min")) || $original.prop("min") === "" ? -Infinity : parseFloat($original.prop("min"))
````

**Comment by shaack** [comment]
Thanks for the report, I will fix it soon
