### ISSUE TITLE
How to updating value on plain javascript ?

### ISSUE THREAD

**Issue by suryatanamas** [shaack/bootstrap-input-spinner#85]
My HTML
`<input type="number" class="buttons-only form-control-sm" id="jumlah1" name="jumlah1" min="0" max="99" value="1" onchange="update(this)">`
Input "Id" was produced by looping operation.

And My Javascript
`// Retrieving data
for (var i = 1; i <= num; i++) {
	var nama = "jumlah" + i;
	var elem = document.getElementById( nama );
	elem.setValue = session_get( nama );
}`
`session_get` was my own function for `sessionStorage` operation.

As you suggest, I already change form `elem.value = session_get( nama )` into `elem.setValue = session_get( nama )`, but still get "1" value on my `input tag`

**Comment by shaack** [comment]
Use it as a function. It should work with `element.setValue(newValue)`.

**Comment by suryatanamas** [comment]
Okay as plain JS was teribble error.
I am used plain JS combine with JQuery as solution
