### ISSUE TITLE
Cannot read value when id contains certain characters

### ISSUE THREAD

**Issue by swayton** [shaack/bootstrap-input-spinner#91]
`<input type="number" id="qty:CRE:S" class="form-control-sm" value="0" min="0" max="1000" step="1"/>`

`$('#qty:CRE:S').val()` results in undefined

Changing `:` to `*`, `.` or `_` results in the same, but replacing with an alphanumeric character will allow value to be read

**Comment by shaack** [comment]
okay, what was it? :)

**Comment by swayton** [comment]
Honestly... not sure!

I've used `allelmts = $("[id^='qty:']");` and iterated though what I needed and it works, just had to filter out any id with an underscore so I'm just reading the original inputs

**Comment by shaack** [comment]
Thanks for your reply. I suppose it might have something to do with the fact that colon is reserved for css syntax, as in ":hover".  But actually I do not know either. :)

**Comment by swayton** [comment]
Probably, just going back so standard javascript without using jQuery works fine, so:

`$('#qty:CRE:S').val()` can be changed to `document.getElementById('qty:CRE:S').value`

**Comment by shaack** [comment]
Yeah right. But, to set the value, ".value =" does not work. You must use setValue(). This is a problem with the spinner I have not solved yet.
And I found something on slashdot about it: https://stackoverflow.com/questions/5552462/handling-colon-in-element-id-with-jquery 
You can escape colons with "\\".
