### ISSUE TITLE
Input spinner does not respond to up/down arrow keys

### ISSUE THREAD

**Issue by jcputney** [shaack/bootstrap-input-spinner#94]
The browser native number input allows for stepping using arrow keys, but this plugin does not work the same way. I've created a pull request (#92) to implement this functionality, including continued stepping when holding down the arrow keys.

**Comment by shaack** [comment]
I haven't gotten around to taking care of the pull yet, unfortunately. Thank you for creating it, I hope to get to it this week.

**Comment by shaack** [comment]
Done. Thanks for your contribution!
