### ISSUE TITLE
Right-click on button sends spinner on endless increment/decrement operation

### ISSUE THREAD

**Issue by cal-zone** [shaack/bootstrap-input-spinner#96]
On Mac Big Sur 11.1 using Safari 14.0.2

If I use right-click (or control-click) on either the + or - button in a spinner, the spinner starts endlessly incrementing or decrementing. The only way to stop it is to click somewhere else to close the contextual menu and then click somewhere else again ( if it's set to a max/min value it will also stop at that limit).

This almost seems like intentional functionality, although I'm not sure what the purpose would be. ((( Sidebar: It would rock if it were tied to a swipe gesture and then decayed (like iOS spinners). That doesn't seem to be what's happening. ))) If the aim is to provide a shortcut for maxing/minning out the field, why not just jump straight to the maximum/min value? 

I stumbled upon this because I often use the contextual menu item "Inspect Element" as a means to jump straight to the region of the code I want to view source on.

**Comment by shaack** [comment]
Hello, thanks for the report. No, it is not intentional, this is a bug. It should do nothing on right-click, as similar as possible to the native spinner https://shaack.com/projekte/bootstrap-input-spinner/test/native-number-input.html
