### ISSUE TITLE
Feature request: display as time support

### ISSUE THREAD

**Issue by cal-zone** [shaack/bootstrap-input-spinner#97]
This may be a little advanced relative to the stated aims of this widget, but I would love it if the spinner were able to display numbers in time format.

So, for example, if I am having a user select a number of hours or minutes, and I have my step set to 0.25, what the user sees is a sequence of 1:15, 1:30, 1:45, 2:00

I believe in keeping it simple, because it's a single spinner and not a time selector, so the above would not distinguish between hours, minutes, or seconds proper. It would just be limited to interpreting (for display purposes only) whatever comes after the decimal point as a proportion of 60, and whatever comes before the decimal point as the normal integer.

Because such an interface would be confusing to a user trying to enter time directly into the field, I also think it would likely be a good case to make the buttonsOnly option on by default when using time display mode.

Just to make sure I'm clear: the value reported to the original field itself remains at all times a standard float. So 2:20 would be stored as 2.333333 (as many decimal as designated in the original field / database defined) behind the scenes. All operations behind the scenes would treat the number as a standard float. The only change would be how it is displayed in the spinner to the user.

Thank you for an awesome plugin in any case!

**Comment by shaack** [comment]
I like the idea. Thanks for your contribution. It could be implemented as a kind of view filter or view interceptor. In Spring this is called "CustomEditor". https://www.baeldung.com/spring-mvc-custom-property-editor It implements the methods „setAsText“ and „getAsText“ to translate from text to the needed format. For the inputSpinner this could be „set/getAsNumber“ or so. A custom editors could be defined in the props of the spinner, like this
```js
customEditor: {
    setAsNumber: function(number) {...},
    getAsNumber: function() {... return number}
}
```

**Comment by shaack** [comment]
With v2.0.0.  Time (H:mm) rendering and parsing is now implemented, see the example "TimeEditor" in the demo page https://shaack.com/projekte/bootstrap-input-spinner/

**Comment by shaack** [comment]
...you can also write other custom editors now for hexadecimal, degrees,... everything
