### ISSUE TITLE
Calculation Error

### ISSUE THREAD

**Issue by alfredovf** [shaack/bootstrap-input-spinner#99]
When you use certain values it seems the calculations it's not working well. Please see this example (is used the demo page):

![Screenshot_1](https://user-images.githubusercontent.com/8105762/113497563-b3c96100-94db-11eb-9198-74cdcc933aca.png)

It occurs to me that the issue is in this line:
![Screenshot_2](https://user-images.githubusercontent.com/8105762/113497619-36522080-94dc-11eb-971a-2d0b588c9d87.png)

It's an issue, or i have to set some particular configuration?

Thanks!

**Comment by shaack** [comment]
Is this a duplicate for https://github.com/shaack/bootstrap-input-spinner/issues/56 ?
